### ISSUE TITLE
upgrade

### ISSUE THREAD

**Issue by dmitr12** [EvgenBuiko/KGIG_Labs#1]
`...
		if (Ind1 < X.rows() && Ind2 <= X.rows())
		{
			GetWindowCoords(X(Ind1), Y(Ind1), xw, yw);
			dc.MoveTo(xw, yw);
			for (int i = Ind1 + Ind2; i < X.rows(); i += Ind2)
			{
				GetWindowCoords(X(i), Y(i), xw, yw);
				dc.LineTo(xw, yw);
			}
		}
...
`
`
void CMainWin::PaintF..(CDC& dc, CRect rw)
...
PaintF..(dc, CRect(300, 50, 700, 400));
...
paint2D.SetWindowRect(rw);
...
`
`
void CMainWin::PaintF1234(CDC& dc)
{
	PaintF1(dc, CRect(100, 50, 300, 200));
	PaintF3(dc, CRect(100, 250, 300, 400));
	PaintF2(dc, CRect(600, 50, 800, 200));
	PaintF4(dc, CRect(600, 250, 800, 400));
}
`

**Comment by EvgenBuiko** [comment]
Thanks
